name: Integration Tests

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  integration:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install Concierge
        run: sudo snap install --classic concierge
      - name: Bootstrap Juju + LXD
        run: sudo concierge prepare --preset machine --extra-snaps astral-uv
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Pack charm
        run: charmcraft pack
      - name: Build dummy-requirer charm
        run: tox -e build-dummy
      - name: Run integration tests
        run: tox -e integration
