name: Release to edge

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv tool install tox --with tox-uv
      - run: tox -e lint

  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv tool install tox --with tox-uv
      - run: tox -e unit

  release:
    needs: [lint, unit]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: latest/edge
          destructive-mode: "true"
